name: Publish |  To GitHub Pages

on:
  pull_request:
    branches:
      - main
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Read .nvmrc
        working-directory: ./projects/veeva-clm/
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'

      - name: Install npm dependencies
        working-directory: ./projects/veeva-clm/
        run: npm i

      - name: Build and Deploy projects
        working-directory: ./projects/veeva-clm/
        run: npm run build-storybook --if-present

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: './projects/veeva-clm/storybook-static'